<?php
require_once('./includes/header.php');
require_once('./includes/navbar.php');
?>
        <main>

            <section class="news-detail-header-section text-center">
                <div class="section-overlay"></div>

                <div class="container">
                    <div class="row">

                        <div class="col-lg-12 col-12">
                            <h1 class="text-white">Terms and Conditions</h1>
                        </div>

                    </div>
                </div>
            </section>

            <section class="news-section section-padding">
                <div class="container">
                    <h5 class="mt-3 mv-3">1) REGISTRATION</h5>
                    <p>By registering, you certify that all information you provide, now or in the future, is consistent. https://optionstrading.com/reserves the right, in its sole discretion, to deny you access to this website or any portion thereof without notice for the following reasons (a) immediately by https://optionstrading.com/for any unauthorized access or use by you (b) immediately by https://optionstrading.com/if you assign or transfer (or attempt the same) any rights granted to you under this Agreement; (c) immediately, if you violate any of the other terms and conditions of this User Agreement. By registering, the client hereby agrees to get periodic SMS Alerts and Newsletters.</p>

                    <h5 class="mt-3 mv-3">2) LICENSE</h5>
                    <p>Options trading.com, hereby grants you a limited, non-exclusive, non-assignable and non-transferable license to access https://optionstrading.com/provided and expressly conditioned upon your agreement that all such access and use shall be governed by all of the terms and conditions set forth in this USER AGREEMENT.</p>

                    <h5 class="mt-3 mv-3">3)  COPYRIGHT & NO RETRANSMISSION OF INFORMATION</h5>
                    <p>https://optionstrading.com/as well as the design and information contained in this site is valuable and exclusive property of Option trading.com, and nothing in this Agreement shall be construed as transferring or assigning any such ownership rights to you or any other person or entity. All information on https://optionstrading.com/is the proprietary and confidential property of https://optionstrading.com/and cannot be repeated for any reason outside Options trading.com. You agree not to repeat or rebroadcast in any way any of the recommendations made on https://optionstrading.com/for any reason whatsoever. You agree that if you do repeat or re-post any of https://optionstrading.com/recommendations by any mean, you will be liable for actual and punitive damages as determined by https://optionstrading.com/and additional damages to be determined by Courts of Law in India.</p>

                    <p>You may not resell, redistribute, broadcast or transfer the information or use the information in a searchable, machine-readable database unless separately and specifically authorized in writing by https://optionstrading.com/prior to such use. You may not rent, lease, sublicense, distribute, transfer, copy, reproduce, publicly display, publish, adapt, store or time-share Options trading.com, any part thereof, or any of the information received or accessed therefrom to or through any other person or entity unless separately and specifically authorized in writing by https://optionstrading.com/prior to such use. In addition, you may not remove, alter or obscure any copyright, legal or proprietary notices in or on any portions of https://optionstrading.com/without prior written authorization except as set forth herein. Any other use of the information contained in this site requires the prior written consent of https://optionstrading.com/and may require a separate fee.</p>

                    <h5 class="mt-3 mv-3">4) DELAYS IN SERVICES</h5>
                    <p>Neither https://optionstrading.com/nor its directors, employees, affiliates, agents, representatives or subcontractors shall be liable for any loss or liability resulting, directly or indirectly, from delays or interruptions due to electronic or mechanical equipment failures, telephone interconnect problems, defects, weather, strikes, walkouts, fire, acts of God, riots, armed conflicts, acts of war, or other like causes. Https://optionstrading.com/shall have no responsibility to provide you access to https://optionstrading.com/while interruption is due to any such cause.</p>

                    <h5 class="mt-3 mv-3">5) LIABILITY DISCLAIMER</h5>
                    <p>You expressly agree that use of the website is at your sole risk. The contents, information, software, products, features and services published on this website may include inaccuracies or typographical errors. Changes are periodically added to the contents hereinafter. https://optionstrading.com/and/or its respective suppliers may make improvements and/or changes in this website at any time. This website may be temporarily unavailable from time to time due to required maintenance, telecommunication interruptions, or other disruptions. https://optionstrading.com/(and its owners, suppliers, consultants, advertisers, affiliates, partners, employees or any other associated entities, all collectively referred to as associated entities hereafter) shall not be liable to user or member or any third party should https://optionstrading.com/exercise its right to modify or discontinue any or all of the contents, information, software, products, features and services published on this website. https://optionstrading.com/and/or its respective associated entities make no representations about the suitability of the contents, information, software, products, features and services contained on this website for any purpose. All such contents, information, software, products, features and services are provided “as is” without warranty of any kind. https://optionstrading.com/and/or its associated entities hereby disclaim all warranties and conditions with regard to these contents, information, software, products, features and services, including all implied warranties and conditions of merchantability, fitness for a particular purpose, title, non-infringement, and availability. In no event shall https://optionstrading.com/and/or its associated entities be liable for any direct, indirect, punitive, incidental, special or consequential damages arising out of or in any way connected with the use of this website or with the delay or inability to use this website, or for any contents, information, software, products, features and services obtained through this website, or otherwise arising out of the use of this website, whether based on contract, tort, strict liability or otherwise, even if https://optionstrading.com/or any of its associated entities have been advised of the possibility of damages.</p>

                    <h5 class="mt-3 mv-3">6) TRADING DISCIPLINE</h5>
                    <p>Options trading strictly follows Trading Principle and Stop Loss Policy wherein Customer by default agree to not do/ enter any trade without Pre Informed/ Defined Stop Loss. If you trade against the stop loss policy, You alone shall be responsible for the same & Options trading shall have zero liability towards it. We further advise that do not trade on recommendations of employees outside the course of employment. In case, if you will do so, the liability will be your own & https://optionstrading.com/shall not be liable/ accountable for any such loss.</p>

                    <h5 class="mt-3 mv-3">7)  USE OF MESSAGE BOARDS, CHAT ROOMS AND OTHER COMMUNICATION FORUMS</h5>
                    <p>If this website contains message/bulletin boards, chat rooms, or other message or communication facilities (collectively, “Forums”), you agree to use the Forums only to send and receive messages and material that are proper and related to the particular Forum. By way of example, and not as a limitation, you agree that when using a Forum, you shall not do any of the following:</p>
                    <p>Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others.</p>
                    <p>ublish, post, distribute or disseminate any defamatory, infringing, obscene, indecent or unlawful material or information.</p>
                    <p>Upload files that contain software or other material protected by intellectual property laws (or by rights of privacy and publicity) unless you own or control the rights thereto or have received all necessary consents.</p>
                    <p>Upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another’s computer</p>
                    <p>Conduct or forward surveys, contests, or chain letters.</p>
                    <p>Download any file posted by another user of a Forum that you know, or reasonably should know, cannot be legally distributed in such manner.</p>

                    <h5 class="mt-3 mv-3">8) EQUIPMENT AND OPERATION</h5>
                    <p>You shall provide and maintain all telephone/internet and other equipment necessary to access Options trading.com, and the costs of any such equipment and/or telephone/internet connections or use, including any applicable taxes, shall be borne solely by you. You are responsible for operating your own equipment used to access optionstrading.com.</p>

                    <h5 class="mt-3 mv-3">9)  INFORMATION DISCLAIMER</h5>
                    <p>You acknowledge that the information provided through https://optionstrading.com/is compiled from sources, which are beyond the control of Options trading.com. Though such information is recognized by the parties to be generally reliable, the parties acknowledge that inaccuracies may occur and https://optionstrading.com/does not warrant the consistency or suitability of the information. For this reason, as well as the possibility of human and mechanical errors and other factors, you acknowledge that https://optionstrading.com/is provided to you on an “as is, with all faults” basis. https://optionstrading.com/expressly disclaims any and all warranties, whether express, oral, implied, statutory or otherwise, of any kind to the users and/or any third party, including any implied warranties of consistency, timeliness, completeness, merchantability and fitness for a particular purpose, as well as any warranties arising by virtue of custom of trade or course of dealing and any implied warranties of title or non-infringement. In addition, Options trading.com, in providing the information makes no endorsement of any particular security, market participant, or brokerage. Further, https://optionstrading.com/does not represent or warrant that it will meet your requirements or is suitable for your needs.</p>
                    <p>Under this User Agreement, you assume all risk of errors and/or omissions in Options trading.com, including the transmission or translation of information. You assume full responsibility for implementing sufficient procedures and checks to satisfy your requirements for the consistency and suitability of Options trading.com, including the information, and for maintaining any means, which you may require for the reconstruction of lost data or subsequent manipulations or analyses of the information under the User Agreement.</p>
                    <p>You agree that https://optionstrading.com/(including its officers, directors, employees, affiliates, group companies agents, representatives or subcontractors) shall not in any event be liable for any special, incidental or consequential damages arising out of the use or inability to use https://optionstrading.com/for any purpose whatsoever. https://optionstrading.com/and its affiliates, associates, officers, directors, employees and agents shall have no liability in tort, contract, or otherwise to user and/or any third party.</p>

                    <h5 class="mt-3 mv-3">10) LINKS TO THIRD PARTY SITES</h5>
                    <p>The links in this site will allow you to leave Options trading.com. The linked sites are not under the control of Options trading.com. https://optionstrading.com/has not reviewed, or approved these sites and is not responsible for the contents or omissions of any linked site or any links contained in a linked site. The inclusion of any linked site does not imply endorsement by https://optionstrading.com/of the site. Third party links to https://optionstrading.com/shall be governed by a separate agreement.</p>
                        
                    <h5 class="mt-3 mv-3">11)  INDEMNIFICATION</h5>
                    <p>You shall indemnify, defend and hold harmless https://optionstrading.com/(including its officers, directors, employees, affiliates, group companies, agents, representatives or subcontractors) from any and all claims and losses imposed on, incurred by or asserted as a result of or related to: (a) your access and use of https://optionstrading.com/(b) any non-compliance by user with the terms and conditions hereof; or (c) any third party actions related to users receipt and use of the information, whether authorized or unauthorized. Any clause declared invalid shall be deemed severable and not affect the validity or enforceability of the remainder. These terms may only be amended in a writing signed by Options trading.com</p>
                        
                    <h5 class="mt-3 mv-3">12) CONFLICTING TERMS</h5>
                    <p>If there is any conflict between this User Agreement and other documents, this User Agreement shall govern, whether such order or other documents is prior to or subsequent to this User Agreement, or is signed or acknowledged by any director, officer, employee, representative or agent of Options trading.com</p>
                    
                    <h5 class="mt-3 mv-3">13) ATTORNEY’S FEES</h5>
                    <p>If https://optionstrading.com/takes action (by itself or through its associate companies) to enforce any of the provisions of this User Agreement, including collection of any amounts due hereunder, https://optionstrading.com/shall be entitled to recover from you (and you agree to pay), in addition to all sums to which it is entitled or any other relief, at law or in equity, reasonable and necessary attorney’s fees and any costs of any litigation.</p>
                        
                    <h5 class="mt-3 mv-3">14) ENTIRE AGREEMENT</h5>
                    <p>This User Agreement constitutes the entire agreement between the parties, and no other agreement, written or oral, exists between you and Options trading.com. By using the Information on Options trading.com., you assume full responsibility for any and all gains and losses, financial, emotional or otherwise, experienced, suffered or incurred by you. https://optionstrading.com/does not guarantee the consistency, completeness or timeliness of, or otherwise endorse in any way, the views, opinions or recommendations expressed in the Information, does not give investment advice, and does not advocate the purchase or sale of any security or investment by you or any other individual. The Information is not intended to provide tax, legal or investment advice, which you should obtain from your professional advisor prior to making any investment of the type discussed in the Information. The Information does not constitute a solicitation by the information providers, https://optionstrading.com/or others for the purchase or sale of securities. The service is provided “as is,” without warranty of any kind, either express or implied, including without limitation, any warranty for information, data, services, uninterrupted access, or products provided through or in connection with the service. specifically, https://optionstrading.com/disclaims any and all warranties, including, but not limited to: (i) Any warranties concerning the availability, consistency, usefulness, or content of information, products or services, and  (ii) Any warranties of title, warranty of non-infringement and warranties of merchantability or fitness for a particular purpose. This disclaimer of liability applies to any damages or injury caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, whether for breach of contract, tort, negligence, or under any other cause of action. Neither https://optionstrading.com/nor any of its employees, agents, successors, assignees, affiliates, group companies or content or service providers shall be liable to you or other third party for any direct, indirect, incidental, special or consequential damages arising out of use of service or inability to gain access to or use the service or out of any breach of any warranty. Because some countries do not allow the exclusion or limitation of liability for consequential or incidental damages, the above limitation may not apply to you. In such countries, the respective liability of Options trading.com, its employees, agents, successors, assignees, affiliates, group companies and content or service providers respective liability is limited to the amount provided under said law.</p>
                        
                    <h5 class="mt-3 mv-3">15)  DISPUTE SETTLEMENT</h5>
                    <p>All disputes, differences and questions of any nature which at any time arise between the parties to this agreement out of the construction of or concerning anything contained in or arising out of this agreement or as to the rights, duties or liabilities under it or the parties to it shall be referred to the sole Arbitrator under the Arbitration and Conciliation Act, 1996. The sole Arbitrator shall be appointed by the Managing Director of Options trading. The Arbitration Proceedings shall be held at Indore (Madhya Pradesh) India. The seat of Arbitration will be at Indore (Madhya Pradesh), India. The laws prevailing in India Shall alone apply to the Arbitration Proceedings between the parties.</p>
                    
                    <h5 class="mt-3 mv-3">16) JURISDICTION</h5>
                    <p>Both the Parties agree that all claims, differences and disputes, including any agreements, contracts and transactions made with reference to anything incidental thereto or in pursuance thereof or relating to their validity, construction, interpretation, fulfilment or the rights, obligations and liabilities of the parties thereto and including any question of whether such dealings, transactions MOA, or contracts have been entered into or not, shall be subject to the exclusive jurisdiction of the Courts of Indore only.</p>
                  </div>
                </div>
            </section>
        </main>
<?php

require_once('includes/footer.php');
?>